version: '3.3'

services:
  node:
    build: .
    ports:
      - "8080:3000"
    hostname: node
    env_file: .env
# ▼ dev環境設定
#     depends_on:
#       - mongodb
  
#   mongodb:
#     image: mongo
#     restart: always
#     ports:
#       - "27018:27017"
#     hostname: mongodb
#     environment:
#       -  'MONGODB_USER=user' 
#       -  'MONGODB_PASS=password!'
#     volumes:
#       - 'mongodb-data:/data/db'

#   mongo-express:
#     container_name: mongo-express
#     links:
#       - 'mongodb:mongo'
#     ports:
#       - '8081:8081'
#     environment:
#       - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
#       - 'ME_CONFIG_BASICAUTH_USERNAME=user'
#       - 'ME_CONFIG_BASICAUTH_PASSWORD=password!'
#     image: mongo-express

#   mongo-data:
#     image: busybox

# volumes: 
#   mongodb-data: